# Site
repository: michael11albrecht.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Michael Albrecht
title: Geodata Science Student @Hochschule München
email: michael.j.a@hotmail.de
email_title: Email
website: michael11albrecht.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username:
github_username:  michael11albrecht
# stackoverflow_username: "00000001"
# dribbble_username: 
# facebook_username: 
# flickr_username: 
instagram_username: michael__albrecht
linkedin_username: michael-albrecht-1241261b7
# xing_username:
# pinterest_username: 
# youtube_username: 
# googleplus_username:
# orcid_username: 

# Additional icon links
# additional_links:
# - title: itsgoingto.be
  #icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Über mich
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, ich bin Michael.

content:
  - title: Projekte # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Snow Base
        link: github.com/michael11albrecht
        # link_text: Project Website
        additional_links:
          - title:  michael11albrecht
            icon: fab fa-github
            url: github.com/michael11albrecht
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Test
        description: | # this will include new lines to allow paragraphs
          Test

  - title: Berufserfahrung # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Allgeier Engineering GmbH, München
        link: https://www.allgeier-engineering.com/
        # link_text: boringcompany.com
        sub_title: Werkstudent Automobil-Infotainment
        caption: 2021 - 2022
        quote: >
          Allgeier Engineering unterstützt seine Kunden bei der Umsetzung herausfordernder (Entwicklungs­)Projekte in der IT­, Automobil­ und Bahntechnik im Bereich der technisch eingebetteten elektronischen Systeme.
        description: | # this will include new lines to allow paragraphs
          - Software-testing
      - layout: left
        title: digiCOM IT-Solutions GmbH & Co. KG, Sonthofen
        link: https://rentmaxx.com/
        # link_text: boringcompany.com
        sub_title: Fachinformatiker für Systemintegration
        caption: 2020 - 2021
        quote: >
          Mit unseren Komplettlösungen digiCOM rentmaxx für die Sportartikelvermietung und digiCOM depotmaxx für die Verwaltung und Steuerung von Skidepots sind wir seit 1997 erfolgreich auf den Wintersportmärkten im In- und Ausland vertreten.
        description: | # this will include new lines to allow paragraphs
          - Technischer Kundensupport im Innen- und Außendienst - Planung und Umsetzung von Kundenprojekten
          - Testen firmeneigener Softwareentwicklungen
          - Beratungsgespräche auf Messen und im Außendienst
          - Hard-/Softwarefehler Diagnose und Behebung
      - layout: left
        title: digiCOM IT-Solutions GmbH & Co. KG, Sonthofen
        link: https://rentmaxx.com/
        # link_text: boringcompany.com
        sub_title: duale Ausbildung zum Fachinformatiker für Systemintegration
        caption: 2017 - 2020
        quote: >
          Mit unseren Komplettlösungen digiCOM rentmaxx für die Sportartikelvermietung und digiCOM depotmaxx für die Verwaltung und Steuerung von Skidepots sind wir seit 1997 erfolgreich auf den Wintersportmärkten im In- und Ausland vertreten.
        description: | # this will include new lines to allow paragraphs
          


  - title: Bildungsweg # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hochschule München
        link: https://sites.hm.edu/mucdai/angebot/geodata_science/studium.de.html
        caption: 2022 -
        sub_title: BSc Geodata Science
        quote: >
          Du lernst sowohl Geoinformation als auch Informatik, Mathematik und KI zu verstehen und miteinander zu verknüpfen.
        description: | # this will include new lines to allow paragraphs
          Bis voraussichtlich 2026

  - title: Persönliche Interessen
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Klettern
      - Skifahren (Alpin/Tour)
      - Surfen

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
